export type StoryPhoto = {
  src: string;
  alt: string;
};

export type Story = {
  slug: string;
  title: string;
  location: string;
  dateLabel: string;
  image: string;
  alt: string;
  summary: string;
  paragraphs: string[];
  related?: { slug: string; label: string };
  gallery: StoryPhoto[];
};

function coverFirst(cover: string, alt: string, photos: StoryPhoto[]): StoryPhoto[] {
  const rest = photos.filter((photo) => photo.src !== cover);
  return [{ src: cover, alt }, ...rest];
}

export const stories: Story[] = [
  {
    slug: "matrimonio-anna-matte-cantu-valmorea",
    title: "250 invitati con la semplicità e la gioia di Anna e Matteo",
    location: "Cantù, Como · Chiesa di San Teodoro, Palazzo Sacchi, Valmorea",
    dateLabel: "22 settembre 2018",
    image: "/media/images/lucea-2018-anna-matte/lucea-2018-anna-matte-lucea-matrimonio-am-cantu-san-teodoro-palazzo-sacchi-valmorea-como-058.webp",
    alt: "Matrimonio di Anna e Matteo a Cantù e Valmorea",
    summary: "250 invitati, chiesa di San Teodoro e Palazzo Sacchi: una festa scout piena di gioia, raccontata in reportage.",
    paragraphs: [
      "Quando si parla di una festa infinita, travolgente e gioiosa, quella del matrimonio di Anna e Matte, in provincia di Como, è stata una delle più grandi: 250 amiche e amici che hanno riempito la chiesa di San Teodoro, Palazzo Sacchi, ma anche i nostri obiettivi e le schede delle nostre macchine fotografiche!",
      "Una vera festa piena di gioia, come solo gli scout sanno fare, dove allegria e condivisione occupano il primo posto assoluto. Le foto di Anna e Matte raccontano i loro sguardi innamorati; quelle dei genitori una profonda emozione; quelle degli amici un'incontenibile felicità. È questo il genere di fotografia di matrimonio che amiamo particolarmente: leggera, spontanea e discreta, capace di mettere gli sposi a proprio agio e di lasciare che siano i festeggiamenti a guidare il racconto.",
      "E così, semplicemente aggirandoci tra le persone, nascono quegli scatti di reportage pieni di vita che più ci rappresentano.",
    ],
    gallery: coverFirst("/media/images/lucea-2018-anna-matte/lucea-2018-anna-matte-lucea-matrimonio-am-cantu-san-teodoro-palazzo-sacchi-valmorea-como-058.webp", "Matrimonio di Anna e Matteo a Cantù e Valmorea", [
      { src: "/media/images/lucea-2018-anna-matte/lucea-2018-anna-matte-lucea-matrimonio-am-cantu-san-teodoro-palazzo-sacchi-valmorea-como-050.webp", alt: "Matrimonio di Anna e Matte, Cantù e Valmorea" },
      { src: "/media/images/lucea-2018-anna-matte/lucea-2018-anna-matte-lucea-matrimonio-am-cantu-san-teodoro-palazzo-sacchi-valmorea-como-031.webp", alt: "Matrimonio di Anna e Matte, Cantù e Valmorea" },
      { src: "/media/images/lucea-2018-anna-matte/lucea-2018-anna-matte-lucea-matrimonio-am-cantu-san-teodoro-palazzo-sacchi-valmorea-como-001.webp", alt: "Matrimonio di Anna e Matte, Cantù e Valmorea" },
      { src: "/media/images/lucea-2018-anna-matte/lucea-2018-anna-matte-lucea-matrimonio-am-cantu-san-teodoro-palazzo-sacchi-valmorea-como-003.webp", alt: "Matrimonio di Anna e Matte, Cantù e Valmorea" },
      { src: "/media/images/lucea-2018-anna-matte/lucea-2018-anna-matte-lucea-matrimonio-am-cantu-san-teodoro-palazzo-sacchi-valmorea-como-006.webp", alt: "Matrimonio di Anna e Matte, Cantù e Valmorea" },
      { src: "/media/images/lucea-2018-anna-matte/lucea-2018-anna-matte-lucea-matrimonio-am-cantu-san-teodoro-palazzo-sacchi-valmorea-como-009.webp", alt: "Matrimonio di Anna e Matte, Cantù e Valmorea" },
      { src: "/media/images/lucea-2018-anna-matte/lucea-2018-anna-matte-lucea-matrimonio-am-cantu-san-teodoro-palazzo-sacchi-valmorea-como-012.webp", alt: "Matrimonio di Anna e Matte, Cantù e Valmorea" },
      { src: "/media/images/lucea-2018-anna-matte/lucea-2018-anna-matte-lucea-matrimonio-am-cantu-san-teodoro-palazzo-sacchi-valmorea-como-015.webp", alt: "Matrimonio di Anna e Matte, Cantù e Valmorea" },
      { src: "/media/images/lucea-2018-anna-matte/lucea-2018-anna-matte-lucea-matrimonio-am-cantu-san-teodoro-palazzo-sacchi-valmorea-como-018.webp", alt: "Matrimonio di Anna e Matte, Cantù e Valmorea" },
      { src: "/media/images/lucea-2018-anna-matte/lucea-2018-anna-matte-lucea-matrimonio-am-cantu-san-teodoro-palazzo-sacchi-valmorea-como-021.webp", alt: "Matrimonio di Anna e Matte, Cantù e Valmorea" },
      { src: "/media/images/lucea-2018-anna-matte/lucea-2018-anna-matte-lucea-matrimonio-am-cantu-san-teodoro-palazzo-sacchi-valmorea-como-024.webp", alt: "Matrimonio di Anna e Matte, Cantù e Valmorea" },
      { src: "/media/images/lucea-2018-anna-matte/lucea-2018-anna-matte-lucea-matrimonio-am-cantu-san-teodoro-palazzo-sacchi-valmorea-como-027.webp", alt: "Matrimonio di Anna e Matte, Cantù e Valmorea" },
      { src: "/media/images/lucea-2018-anna-matte/lucea-2018-anna-matte-lucea-matrimonio-am-cantu-san-teodoro-palazzo-sacchi-valmorea-como-030.webp", alt: "Matrimonio di Anna e Matte, Cantù e Valmorea" },
      { src: "/media/images/lucea-2018-anna-matte/lucea-2018-anna-matte-lucea-matrimonio-am-cantu-san-teodoro-palazzo-sacchi-valmorea-como-033.webp", alt: "Matrimonio di Anna e Matte, Cantù e Valmorea" },
      { src: "/media/images/lucea-2018-anna-matte/lucea-2018-anna-matte-lucea-matrimonio-am-cantu-san-teodoro-palazzo-sacchi-valmorea-como-036.webp", alt: "Matrimonio di Anna e Matte, Cantù e Valmorea" },
      { src: "/media/images/lucea-2018-anna-matte/lucea-2018-anna-matte-lucea-matrimonio-am-cantu-san-teodoro-palazzo-sacchi-valmorea-como-039.webp", alt: "Matrimonio di Anna e Matte, Cantù e Valmorea" },
      { src: "/media/images/lucea-2018-anna-matte/lucea-2018-anna-matte-lucea-matrimonio-am-cantu-san-teodoro-palazzo-sacchi-valmorea-como-042.webp", alt: "Matrimonio di Anna e Matte, Cantù e Valmorea" },
      { src: "/media/images/lucea-2018-anna-matte/lucea-2018-anna-matte-lucea-matrimonio-am-cantu-san-teodoro-palazzo-sacchi-valmorea-como-045.webp", alt: "Matrimonio di Anna e Matte, Cantù e Valmorea" },
      { src: "/media/images/lucea-2018-anna-matte/lucea-2018-anna-matte-lucea-matrimonio-am-cantu-san-teodoro-palazzo-sacchi-valmorea-como-048.webp", alt: "Matrimonio di Anna e Matte, Cantù e Valmorea" },
      { src: "/media/images/lucea-2018-anna-matte/lucea-2018-anna-matte-lucea-matrimonio-am-cantu-san-teodoro-palazzo-sacchi-valmorea-como-051.webp", alt: "Matrimonio di Anna e Matte, Cantù e Valmorea" },
      { src: "/media/images/lucea-2018-anna-matte/lucea-2018-anna-matte-lucea-matrimonio-am-cantu-san-teodoro-palazzo-sacchi-valmorea-como-054.webp", alt: "Matrimonio di Anna e Matte, Cantù e Valmorea" },
      { src: "/media/images/lucea-2018-anna-matte/lucea-2018-anna-matte-lucea-matrimonio-am-cantu-san-teodoro-palazzo-sacchi-valmorea-como-057.webp", alt: "Matrimonio di Anna e Matte, Cantù e Valmorea" },
      { src: "/media/images/lucea-2018-anna-matte/lucea-2018-anna-matte-lucea-matrimonio-am-cantu-san-teodoro-palazzo-sacchi-valmorea-como-059.webp", alt: "Matrimonio di Anna e Matte, Cantù e Valmorea" },
      { src: "/media/images/lucea-2018-anna-matte/lucea-2018-anna-matte-lucea-matrimonio-am-cantu-san-teodoro-palazzo-sacchi-valmorea-como-062.webp", alt: "Matrimonio di Anna e Matte, Cantù e Valmorea" },
      { src: "/media/images/lucea-2018-anna-matte/lucea-2018-anna-matte-lucea-matrimonio-am-cantu-san-teodoro-palazzo-sacchi-valmorea-como-065.webp", alt: "Matrimonio di Anna e Matte, Cantù e Valmorea" },
      { src: "/media/images/lucea-2018-anna-matte/lucea-2018-anna-matte-lucea-matrimonio-am-cantu-san-teodoro-palazzo-sacchi-valmorea-como-068.webp", alt: "Matrimonio di Anna e Matte, Cantù e Valmorea" },
      { src: "/media/images/lucea-2018-anna-matte/lucea-2018-anna-matte-lucea-matrimonio-am-cantu-san-teodoro-palazzo-sacchi-valmorea-como-071.webp", alt: "Matrimonio di Anna e Matte, Cantù e Valmorea" },
      { src: "/media/images/lucea-2018-anna-matte/lucea-2018-anna-matte-lucea-matrimonio-am-cantu-san-teodoro-palazzo-sacchi-valmorea-como-074.webp", alt: "Matrimonio di Anna e Matte, Cantù e Valmorea" },
      { src: "/media/images/lucea-2018-anna-matte/lucea-2018-anna-matte-lucea-matrimonio-am-cantu-san-teodoro-palazzo-sacchi-valmorea-como-077.webp", alt: "Matrimonio di Anna e Matte, Cantù e Valmorea" },
      { src: "/media/images/lucea-2018-anna-matte/lucea-2018-anna-matte-lucea-matrimonio-am-cantu-san-teodoro-palazzo-sacchi-valmorea-como-080.webp", alt: "Matrimonio di Anna e Matte, Cantù e Valmorea" },
      { src: "/media/images/lucea-2018-anna-matte/lucea-2018-anna-matte-lucea-matrimonio-am-cantu-san-teodoro-palazzo-sacchi-valmorea-como-083.webp", alt: "Matrimonio di Anna e Matte, Cantù e Valmorea" },
      { src: "/media/images/lucea-2018-anna-matte/lucea-2018-anna-matte-lucea-matrimonio-am-cantu-san-teodoro-palazzo-sacchi-valmorea-como-086.webp", alt: "Matrimonio di Anna e Matte, Cantù e Valmorea" },
      { src: "/media/images/lucea-2018-anna-matte/lucea-2018-anna-matte-lucea-matrimonio-am-cantu-san-teodoro-palazzo-sacchi-valmorea-como-089.webp", alt: "Matrimonio di Anna e Matte, Cantù e Valmorea" },
      { src: "/media/images/lucea-2018-anna-matte/lucea-2018-anna-matte-lucea-matrimonio-am-cantu-san-teodoro-palazzo-sacchi-valmorea-como-092.webp", alt: "Matrimonio di Anna e Matte, Cantù e Valmorea" },
      { src: "/media/images/lucea-2018-anna-matte/lucea-2018-anna-matte-lucea-matrimonio-am-cantu-san-teodoro-palazzo-sacchi-valmorea-como-095.webp", alt: "Matrimonio di Anna e Matte, Cantù e Valmorea" },
      { src: "/media/images/lucea-2018-anna-matte/lucea-2018-anna-matte-lucea-matrimonio-am-cantu-san-teodoro-palazzo-sacchi-valmorea-como-098.webp", alt: "Matrimonio di Anna e Matte, Cantù e Valmorea" },
      { src: "/media/images/lucea-2018-anna-matte/lucea-2018-anna-matte-lucea-matrimonio-am-cantu-san-teodoro-palazzo-sacchi-valmorea-como-101.webp", alt: "Matrimonio di Anna e Matte, Cantù e Valmorea" },
      { src: "/media/images/lucea-2018-anna-matte/lucea-2018-anna-matte-lucea-matrimonio-am-cantu-san-teodoro-palazzo-sacchi-valmorea-como-104.webp", alt: "Matrimonio di Anna e Matte, Cantù e Valmorea" },
      { src: "/media/images/lucea-2018-anna-matte/lucea-2018-anna-matte-lucea-matrimonio-am-cantu-san-teodoro-palazzo-sacchi-valmorea-como-107.webp", alt: "Matrimonio di Anna e Matte, Cantù e Valmorea" },
      { src: "/media/images/lucea-2018-anna-matte/lucea-2018-anna-matte-lucea-matrimonio-am-cantu-san-teodoro-palazzo-sacchi-valmorea-como-110.webp", alt: "Matrimonio di Anna e Matte, Cantù e Valmorea" },
      { src: "/media/images/lucea-2018-anna-matte/lucea-2018-anna-matte-lucea-matrimonio-am-cantu-san-teodoro-palazzo-sacchi-valmorea-como-113.webp", alt: "Matrimonio di Anna e Matte, Cantù e Valmorea" },
      { src: "/media/images/lucea-2018-anna-matte/lucea-2018-anna-matte-lucea-matrimonio-am-cantu-san-teodoro-palazzo-sacchi-valmorea-como-116.webp", alt: "Matrimonio di Anna e Matte, Cantù e Valmorea" },
    ]),
  },
  {
    slug: "prewedding-michi-tia-boschi-cantu",
    title: "Pre-matrimonio nei boschi con Micaela e Mattia",
    location: "Fecchio, Cantù, Como · Cascina Santa Naga",
    dateLabel: "1 febbraio 2025",
    image: "/media/images/lucea-2025-michi-e-tia/lucea-2025-michi-e-tia-prewedding-lucea-prematrimonio-mt-cantu-boschi-santa-naga-005.webp",
    alt: "Prematrimonio di Micaela e Mattia nei boschi di Cantù",
    summary: "Un febbraio mite a Cascina Santa Naga, tra boschi e nebbiolina, per i biglietti di invito di Tia e Michi.",
    paragraphs: [
      "Erano i primi giorni di febbraio: i più freddi, ma non quel giorno. Appuntamento con Tia e Michi a Fecchio, nel comune di Cantù, vicino al Lago di Como, per andare insieme alla Cascina Santa Naga e scattare qualche foto… da innamorati!",
      "Dopo qualche mese, in agosto, si sarebbero sposati [a Villa Ghiringhelli di Azzate](/storie/matrimonio-michi-tia-villa-ghiringhelli) e volevano creare biglietti di invito personalizzati con i loro volti. Bellissimi, Tia e Michi, sorridenti in ogni momento: innamoratissimi! Santa Naga è un luogo conosciuto da tutti i giovani della zona, con i boschi, i prati, i binari della linea Como-Lecco quasi in disuso e le rovine della cascina.",
      "Il cielo azzurro di febbraio, il sole basso e la nebbiolina del mattino hanno creato un contesto meraviglioso. Siamo entrati subito in sintonia per un servizio fotografico pre-matrimoniale fatto di semplicità, amicizia, leggerezza e anche tenerezza.",
    ],
    related: { slug: "matrimonio-michi-tia-villa-ghiringhelli", label: "il loro matrimonio a Villa Ghiringhelli" },
    gallery: coverFirst("/media/images/lucea-2025-michi-e-tia/lucea-2025-michi-e-tia-prewedding-lucea-prematrimonio-mt-cantu-boschi-santa-naga-005.webp", "Prematrimonio di Micaela e Mattia nei boschi di Cantù", [
      { src: "/media/images/lucea-2025-michi-e-tia/lucea-2025-michi-e-tia-prewedding-lucea-prematrimonio-mt-cantu-boschi-santa-naga-010.webp", alt: "Prematrimonio di Michi e Tia nei boschi di Cantù" },
      { src: "/media/images/lucea-2025-michi-e-tia/lucea-2025-michi-e-tia-prewedding-lucea-prematrimonio-mt-cantu-boschi-santa-naga-005.webp", alt: "Prematrimonio di Micaela e Mattia nei boschi di Cantù" },
      { src: "/media/images/lucea-2025-michi-e-tia/lucea-2025-michi-e-tia-prewedding-lucea-prematrimonio-mt-cantu-boschi-santa-naga-001.webp", alt: "Prematrimonio di Michi e Tia nei boschi di Cantù" },
      { src: "/media/images/lucea-2025-michi-e-tia/lucea-2025-michi-e-tia-prewedding-lucea-prematrimonio-mt-cantu-boschi-santa-naga-002.webp", alt: "Prematrimonio di Michi e Tia nei boschi di Cantù" },
      { src: "/media/images/lucea-2025-michi-e-tia/lucea-2025-michi-e-tia-prewedding-lucea-prematrimonio-mt-cantu-boschi-santa-naga-003.webp", alt: "Prematrimonio di Michi e Tia nei boschi di Cantù" },
      { src: "/media/images/lucea-2025-michi-e-tia/lucea-2025-michi-e-tia-prewedding-lucea-prematrimonio-mt-cantu-boschi-santa-naga-004.webp", alt: "Prematrimonio di Michi e Tia nei boschi di Cantù" },
      { src: "/media/images/lucea-2025-michi-e-tia/lucea-2025-michi-e-tia-prewedding-lucea-prematrimonio-mt-cantu-boschi-santa-naga-006.webp", alt: "Prematrimonio di Michi e Tia nei boschi di Cantù" },
      { src: "/media/images/lucea-2025-michi-e-tia/lucea-2025-michi-e-tia-prewedding-lucea-prematrimonio-mt-cantu-boschi-santa-naga-007.webp", alt: "Prematrimonio di Michi e Tia nei boschi di Cantù" },
      { src: "/media/images/lucea-2025-michi-e-tia/lucea-2025-michi-e-tia-prewedding-lucea-prematrimonio-mt-cantu-boschi-santa-naga-008.webp", alt: "Prematrimonio di Michi e Tia nei boschi di Cantù" },
      { src: "/media/images/lucea-2025-michi-e-tia/lucea-2025-michi-e-tia-prewedding-lucea-prematrimonio-mt-cantu-boschi-santa-naga-009.webp", alt: "Prematrimonio di Michi e Tia nei boschi di Cantù" },
      { src: "/media/images/lucea-2025-michi-e-tia/lucea-2025-michi-e-tia-prewedding-lucea-prematrimonio-mt-cantu-boschi-santa-naga-011.webp", alt: "Prematrimonio di Michi e Tia nei boschi di Cantù" },
      { src: "/media/images/lucea-2025-michi-e-tia/lucea-2025-michi-e-tia-prewedding-lucea-prematrimonio-mt-cantu-boschi-santa-naga-012.webp", alt: "Prematrimonio di Michi e Tia nei boschi di Cantù" },
      { src: "/media/images/lucea-2025-michi-e-tia/lucea-2025-michi-e-tia-prewedding-lucea-prematrimonio-mt-cantu-boschi-santa-naga-013.webp", alt: "Prematrimonio di Michi e Tia nei boschi di Cantù" },
      { src: "/media/images/lucea-2025-michi-e-tia/lucea-2025-michi-e-tia-prewedding-lucea-prematrimonio-mt-cantu-boschi-santa-naga-014.webp", alt: "Prematrimonio di Michi e Tia nei boschi di Cantù" },
      { src: "/media/images/lucea-2025-michi-e-tia/lucea-2025-michi-e-tia-prewedding-lucea-prematrimonio-mt-cantu-boschi-santa-naga-015.webp", alt: "Prematrimonio di Michi e Tia nei boschi di Cantù" },
    ]),
  },
  {
    slug: "matrimonio-yuri-marco-abbiategrasso",
    title: "Yuri e Marco a Cascina Palazzo",
    location: "Palazzo Reale, Sala degli Specchi, Milano · Cascina Palazzo, Abbiategrasso",
    dateLabel: "5 aprile 2025",
    image: "/media/images/lucea-2025-yuri-marco/lucea-2025-yuri-marco-lucea-matrimonio-ym-milano-sala-specchi-cascina-palazzo-abbiategrasso-025.webp",
    alt: "Unione civile di Yuri e Marco a Milano e Abbiategrasso",
    summary: "Dalla Sala degli Specchi di Milano alla Cascina Palazzo: un'unione civile intima, e il trailer video al tramonto.",
    paragraphs: [
      "Dire che l'unione civile di Yuri e Marco è stata commovente non basta, perché l'intimità e la passione che abbiamo potuto respirare — e fotografare! — hanno davvero ispirato il nostro lavoro.",
      "Fin dalla cerimonia nella Sala degli Specchi del Comune di Milano abbiamo sentito queste emozioni, che hanno accompagnato anche la festa. È alla Cascina Palazzo di Abbiategrasso che Yuri e Marco hanno voluto fare una seconda cerimonia simbolica, ancora più intima. Ed è qui che, al tramonto, abbiamo realizzato le riprese per il trailer video che gli sposi ci hanno chiesto, seguendo i loro desideri.",
      "E poi festeggiamenti! Amiche, amici e parenti, tra cui Marika e Fabio, un'altra coppia di sposi che abbiamo conosciuto anni fa con le nostre fotografie e i nostri video.",
    ],
    gallery: coverFirst("/media/images/lucea-2025-yuri-marco/lucea-2025-yuri-marco-lucea-matrimonio-ym-milano-sala-specchi-cascina-palazzo-abbiategrasso-025.webp", "Unione civile di Yuri e Marco a Milano e Abbiategrasso", [
      { src: "/media/images/lucea-2025-yuri-marco/lucea-2025-yuri-marco-lucea-matrimonio-ym-milano-sala-specchi-cascina-palazzo-abbiategrasso-025.webp", alt: "Unione civile di Yuri e Marco a Milano e Abbiategrasso" },
      { src: "/media/images/lucea-2025-yuri-marco/lucea-2025-yuri-marco-lucea-matrimonio-ym-milano-sala-specchi-cascina-palazzo-abbiategrasso-016.webp", alt: "Matrimonio di Yuri e Marco ad Abbiategrasso" },
      { src: "/media/images/lucea-2025-yuri-marco/lucea-2025-yuri-marco-lucea-matrimonio-ym-milano-sala-specchi-cascina-palazzo-abbiategrasso-001.webp", alt: "Matrimonio di Yuri e Marco ad Abbiategrasso" },
      { src: "/media/images/lucea-2025-yuri-marco/lucea-2025-yuri-marco-lucea-matrimonio-ym-milano-sala-specchi-cascina-palazzo-abbiategrasso-003.webp", alt: "Matrimonio di Yuri e Marco ad Abbiategrasso" },
      { src: "/media/images/lucea-2025-yuri-marco/lucea-2025-yuri-marco-lucea-matrimonio-ym-milano-sala-specchi-cascina-palazzo-abbiategrasso-005.webp", alt: "Matrimonio di Yuri e Marco ad Abbiategrasso" },
      { src: "/media/images/lucea-2025-yuri-marco/lucea-2025-yuri-marco-lucea-matrimonio-ym-milano-sala-specchi-cascina-palazzo-abbiategrasso-007.webp", alt: "Matrimonio di Yuri e Marco ad Abbiategrasso" },
      { src: "/media/images/lucea-2025-yuri-marco/lucea-2025-yuri-marco-lucea-matrimonio-ym-milano-sala-specchi-cascina-palazzo-abbiategrasso-009.webp", alt: "Matrimonio di Yuri e Marco ad Abbiategrasso" },
      { src: "/media/images/lucea-2025-yuri-marco/lucea-2025-yuri-marco-lucea-matrimonio-ym-milano-sala-specchi-cascina-palazzo-abbiategrasso-011.webp", alt: "Matrimonio di Yuri e Marco ad Abbiategrasso" },
      { src: "/media/images/lucea-2025-yuri-marco/lucea-2025-yuri-marco-lucea-matrimonio-ym-milano-sala-specchi-cascina-palazzo-abbiategrasso-014.webp", alt: "Matrimonio di Yuri e Marco ad Abbiategrasso" },
      { src: "/media/images/lucea-2025-yuri-marco/lucea-2025-yuri-marco-lucea-matrimonio-ym-milano-sala-specchi-cascina-palazzo-abbiategrasso-018.webp", alt: "Matrimonio di Yuri e Marco ad Abbiategrasso" },
      { src: "/media/images/lucea-2025-yuri-marco/lucea-2025-yuri-marco-lucea-matrimonio-ym-milano-sala-specchi-cascina-palazzo-abbiategrasso-020.webp", alt: "Matrimonio di Yuri e Marco ad Abbiategrasso" },
      { src: "/media/images/lucea-2025-yuri-marco/lucea-2025-yuri-marco-lucea-matrimonio-ym-milano-sala-specchi-cascina-palazzo-abbiategrasso-022.webp", alt: "Matrimonio di Yuri e Marco ad Abbiategrasso" },
      { src: "/media/images/lucea-2025-yuri-marco/lucea-2025-yuri-marco-lucea-matrimonio-ym-milano-sala-specchi-cascina-palazzo-abbiategrasso-024.webp", alt: "Matrimonio di Yuri e Marco ad Abbiategrasso" },
      { src: "/media/images/lucea-2025-yuri-marco/lucea-2025-yuri-marco-lucea-matrimonio-ym-milano-sala-specchi-cascina-palazzo-abbiategrasso-027.webp", alt: "Matrimonio di Yuri e Marco ad Abbiategrasso" },
      { src: "/media/images/lucea-2025-yuri-marco/lucea-2025-yuri-marco-lucea-matrimonio-ym-milano-sala-specchi-cascina-palazzo-abbiategrasso-029.webp", alt: "Matrimonio di Yuri e Marco ad Abbiategrasso" },
      { src: "/media/images/lucea-2025-yuri-marco/lucea-2025-yuri-marco-lucea-matrimonio-ym-milano-sala-specchi-cascina-palazzo-abbiategrasso-031.webp", alt: "Matrimonio di Yuri e Marco ad Abbiategrasso" },
      { src: "/media/images/lucea-2025-yuri-marco/lucea-2025-yuri-marco-lucea-matrimonio-ym-milano-sala-specchi-cascina-palazzo-abbiategrasso-033.webp", alt: "Matrimonio di Yuri e Marco ad Abbiategrasso" },
      { src: "/media/images/lucea-2025-yuri-marco/lucea-2025-yuri-marco-lucea-matrimonio-ym-milano-sala-specchi-cascina-palazzo-abbiategrasso-035.webp", alt: "Matrimonio di Yuri e Marco ad Abbiategrasso" },
      { src: "/media/images/lucea-2025-yuri-marco/lucea-2025-yuri-marco-lucea-matrimonio-ym-milano-sala-specchi-cascina-palazzo-abbiategrasso-037.webp", alt: "Matrimonio di Yuri e Marco ad Abbiategrasso" },
      { src: "/media/images/lucea-2025-yuri-marco/lucea-2025-yuri-marco-lucea-matrimonio-ym-milano-sala-specchi-cascina-palazzo-abbiategrasso-040.webp", alt: "Matrimonio di Yuri e Marco ad Abbiategrasso" },
      { src: "/media/images/lucea-2025-yuri-marco/lucea-2025-yuri-marco-lucea-matrimonio-ym-milano-sala-specchi-cascina-palazzo-abbiategrasso-042.webp", alt: "Matrimonio di Yuri e Marco ad Abbiategrasso" },
      { src: "/media/images/lucea-2025-yuri-marco/lucea-2025-yuri-marco-lucea-matrimonio-ym-milano-sala-specchi-cascina-palazzo-abbiategrasso-bn-002.webp", alt: "Matrimonio di Yuri e Marco ad Abbiategrasso" },
      { src: "/media/images/lucea-2025-yuri-marco/lucea-2025-yuri-marco-lucea-matrimonio-ym-milano-sala-specchi-cascina-palazzo-abbiategrasso-bn-004.webp", alt: "Matrimonio di Yuri e Marco ad Abbiategrasso" },
      { src: "/media/images/lucea-2025-yuri-marco/lucea-2025-yuri-marco-lucea-matrimonio-ym-milano-sala-specchi-cascina-palazzo-abbiategrasso-bn-006.webp", alt: "Matrimonio di Yuri e Marco ad Abbiategrasso" },
      { src: "/media/images/lucea-2025-yuri-marco/lucea-2025-yuri-marco-lucea-matrimonio-ym-milano-sala-specchi-cascina-palazzo-abbiategrasso-bn-009.webp", alt: "Matrimonio di Yuri e Marco ad Abbiategrasso" },
    ]),
  },
  {
    slug: "matrimonio-laura-roberto-magenta",
    title: "Da Palazzo Reale alla Cascina Pietrasanta",
    location: "Palazzo Reale, Milano · Cascina Pietrasanta, Magenta",
    dateLabel: "6 giugno 2025",
    image: "/media/images/lucea-2025-laura-roberto/lucea-2025-laura-roberto-lucea-matrimonio-lr-milano-sala-specchi-cascina-pietrasanta-magenta-070.webp",
    alt: "Matrimonio di Laura e Roberto a Palazzo Reale e Cascina Pietrasanta",
    summary: "Tram da sposa, Sala degli Specchi, kilt e Lego: la festa di Laura e Roberto tra Milano e Magenta.",
    paragraphs: [
      "Se devo pensare ad amici folli invitati a un matrimonio, mi vengono subito in mente quelli di Laura e Roberto: Godzilla, Guerre Stellari, il cerimoniere vestito prima da cardinale e poi da re egizio, amici in kilt…! Le sorprese e la vicinanza degli amici agli sposi sono state la vera gioia di questa giornata.",
      "Laura ha raggiunto il luogo della cerimonia su un tram di linea, vestita da sposa e accompagnata dalle due testimoni. Destinazione: Palazzo Reale di Milano, nella splendida Sala degli Specchi, dove ritorniamo sempre molto volentieri. È qui che all'amico cerimoniere, vestito da cardinale, non è stato permesso di indossare la fascia tricolore!",
      "Ma, a parte questo piccolo aneddoto, tutto è stato incredibilmente divertente, con un bis di cerimonia simbolica celebrata alla Cascina Pietrasanta di Magenta: Lego, birra, salsicce, calcetto, locandine di film degli anni '80 e '90… non è mancato nulla alla festa di questi sposi. Nemmeno la sorpresa finale fatta trovare dagli amici sulla loro auto, direttamente dalla stalla!",
    ],
    gallery: coverFirst("/media/images/lucea-2025-laura-roberto/lucea-2025-laura-roberto-lucea-matrimonio-lr-milano-sala-specchi-cascina-pietrasanta-magenta-070.webp", "Matrimonio di Laura e Roberto a Palazzo Reale e Cascina Pietrasanta", [
      { src: "/media/images/lucea-2025-laura-roberto/lucea-2025-laura-roberto-lucea-matrimonio-lr-milano-sala-specchi-cascina-pietrasanta-magenta-050.webp", alt: "Matrimonio di Laura e Roberto a Magenta" },
      { src: "/media/images/lucea-2025-laura-roberto/lucea-2025-laura-roberto-lucea-matrimonio-lr-milano-sala-specchi-cascina-pietrasanta-magenta-026.webp", alt: "Matrimonio di Laura e Roberto a Magenta" },
      { src: "/media/images/lucea-2025-laura-roberto/lucea-2025-laura-roberto-lucea-matrimonio-lr-milano-sala-specchi-cascina-pietrasanta-magenta-001.webp", alt: "Matrimonio di Laura e Roberto a Magenta" },
      { src: "/media/images/lucea-2025-laura-roberto/lucea-2025-laura-roberto-lucea-matrimonio-lr-milano-sala-specchi-cascina-pietrasanta-magenta-003.webp", alt: "Matrimonio di Laura e Roberto a Magenta" },
      { src: "/media/images/lucea-2025-laura-roberto/lucea-2025-laura-roberto-lucea-matrimonio-lr-milano-sala-specchi-cascina-pietrasanta-magenta-006.webp", alt: "Matrimonio di Laura e Roberto a Magenta" },
      { src: "/media/images/lucea-2025-laura-roberto/lucea-2025-laura-roberto-lucea-matrimonio-lr-milano-sala-specchi-cascina-pietrasanta-magenta-009.webp", alt: "Matrimonio di Laura e Roberto a Magenta" },
      { src: "/media/images/lucea-2025-laura-roberto/lucea-2025-laura-roberto-lucea-matrimonio-lr-milano-sala-specchi-cascina-pietrasanta-magenta-012.webp", alt: "Matrimonio di Laura e Roberto a Magenta" },
      { src: "/media/images/lucea-2025-laura-roberto/lucea-2025-laura-roberto-lucea-matrimonio-lr-milano-sala-specchi-cascina-pietrasanta-magenta-015.webp", alt: "Matrimonio di Laura e Roberto a Magenta" },
      { src: "/media/images/lucea-2025-laura-roberto/lucea-2025-laura-roberto-lucea-matrimonio-lr-milano-sala-specchi-cascina-pietrasanta-magenta-018.webp", alt: "Matrimonio di Laura e Roberto a Magenta" },
      { src: "/media/images/lucea-2025-laura-roberto/lucea-2025-laura-roberto-lucea-matrimonio-lr-milano-sala-specchi-cascina-pietrasanta-magenta-021.webp", alt: "Matrimonio di Laura e Roberto a Magenta" },
      { src: "/media/images/lucea-2025-laura-roberto/lucea-2025-laura-roberto-lucea-matrimonio-lr-milano-sala-specchi-cascina-pietrasanta-magenta-023.webp", alt: "Matrimonio di Laura e Roberto a Magenta" },
      { src: "/media/images/lucea-2025-laura-roberto/lucea-2025-laura-roberto-lucea-matrimonio-lr-milano-sala-specchi-cascina-pietrasanta-magenta-029.webp", alt: "Matrimonio di Laura e Roberto a Magenta" },
      { src: "/media/images/lucea-2025-laura-roberto/lucea-2025-laura-roberto-lucea-matrimonio-lr-milano-sala-specchi-cascina-pietrasanta-magenta-032.webp", alt: "Matrimonio di Laura e Roberto a Magenta" },
      { src: "/media/images/lucea-2025-laura-roberto/lucea-2025-laura-roberto-lucea-matrimonio-lr-milano-sala-specchi-cascina-pietrasanta-magenta-035.webp", alt: "Matrimonio di Laura e Roberto a Magenta" },
      { src: "/media/images/lucea-2025-laura-roberto/lucea-2025-laura-roberto-lucea-matrimonio-lr-milano-sala-specchi-cascina-pietrasanta-magenta-038.webp", alt: "Matrimonio di Laura e Roberto a Magenta" },
      { src: "/media/images/lucea-2025-laura-roberto/lucea-2025-laura-roberto-lucea-matrimonio-lr-milano-sala-specchi-cascina-pietrasanta-magenta-041.webp", alt: "Matrimonio di Laura e Roberto a Magenta" },
      { src: "/media/images/lucea-2025-laura-roberto/lucea-2025-laura-roberto-lucea-matrimonio-lr-milano-sala-specchi-cascina-pietrasanta-magenta-043.webp", alt: "Matrimonio di Laura e Roberto a Magenta" },
      { src: "/media/images/lucea-2025-laura-roberto/lucea-2025-laura-roberto-lucea-matrimonio-lr-milano-sala-specchi-cascina-pietrasanta-magenta-046.webp", alt: "Matrimonio di Laura e Roberto a Magenta" },
      { src: "/media/images/lucea-2025-laura-roberto/lucea-2025-laura-roberto-lucea-matrimonio-lr-milano-sala-specchi-cascina-pietrasanta-magenta-049.webp", alt: "Matrimonio di Laura e Roberto a Magenta" },
      { src: "/media/images/lucea-2025-laura-roberto/lucea-2025-laura-roberto-lucea-matrimonio-lr-milano-sala-specchi-cascina-pietrasanta-magenta-052.webp", alt: "Matrimonio di Laura e Roberto a Magenta" },
      { src: "/media/images/lucea-2025-laura-roberto/lucea-2025-laura-roberto-lucea-matrimonio-lr-milano-sala-specchi-cascina-pietrasanta-magenta-055.webp", alt: "Matrimonio di Laura e Roberto a Magenta" },
      { src: "/media/images/lucea-2025-laura-roberto/lucea-2025-laura-roberto-lucea-matrimonio-lr-milano-sala-specchi-cascina-pietrasanta-magenta-058.webp", alt: "Matrimonio di Laura e Roberto a Magenta" },
      { src: "/media/images/lucea-2025-laura-roberto/lucea-2025-laura-roberto-lucea-matrimonio-lr-milano-sala-specchi-cascina-pietrasanta-magenta-061.webp", alt: "Matrimonio di Laura e Roberto a Magenta" },
      { src: "/media/images/lucea-2025-laura-roberto/lucea-2025-laura-roberto-lucea-matrimonio-lr-milano-sala-specchi-cascina-pietrasanta-magenta-063.webp", alt: "Matrimonio di Laura e Roberto a Magenta" },
      { src: "/media/images/lucea-2025-laura-roberto/lucea-2025-laura-roberto-lucea-matrimonio-lr-milano-sala-specchi-cascina-pietrasanta-magenta-066.webp", alt: "Matrimonio di Laura e Roberto a Magenta" },
      { src: "/media/images/lucea-2025-laura-roberto/lucea-2025-laura-roberto-lucea-matrimonio-lr-milano-sala-specchi-cascina-pietrasanta-magenta-069.webp", alt: "Matrimonio di Laura e Roberto a Magenta" },
      { src: "/media/images/lucea-2025-laura-roberto/lucea-2025-laura-roberto-lucea-matrimonio-lr-milano-sala-specchi-cascina-pietrasanta-magenta-072.webp", alt: "Matrimonio di Laura e Roberto a Magenta" },
      { src: "/media/images/lucea-2025-laura-roberto/lucea-2025-laura-roberto-lucea-matrimonio-lr-milano-sala-specchi-cascina-pietrasanta-magenta-bn-001.webp", alt: "Matrimonio di Laura e Roberto a Magenta" },
      { src: "/media/images/lucea-2025-laura-roberto/lucea-2025-laura-roberto-lucea-matrimonio-lr-milano-sala-specchi-cascina-pietrasanta-magenta-bn-004.webp", alt: "Matrimonio di Laura e Roberto a Magenta" },
      { src: "/media/images/lucea-2025-laura-roberto/lucea-2025-laura-roberto-lucea-matrimonio-lr-milano-sala-specchi-cascina-pietrasanta-magenta-bn-007.webp", alt: "Matrimonio di Laura e Roberto a Magenta" },
      { src: "/media/images/lucea-2025-laura-roberto/lucea-2025-laura-roberto-lucea-matrimonio-lr-milano-sala-specchi-cascina-pietrasanta-magenta-bn-009.webp", alt: "Matrimonio di Laura e Roberto a Magenta" },
      { src: "/media/images/lucea-2025-laura-roberto/lucea-2025-laura-roberto-lucea-matrimonio-lr-milano-sala-specchi-cascina-pietrasanta-magenta-bn-012.webp", alt: "Matrimonio di Laura e Roberto a Magenta" },
      { src: "/media/images/lucea-2025-laura-roberto/lucea-2025-laura-roberto-lucea-matrimonio-lr-milano-sala-specchi-cascina-pietrasanta-magenta-bn-015.webp", alt: "Matrimonio di Laura e Roberto a Magenta" },
      { src: "/media/images/lucea-2025-laura-roberto/lucea-2025-laura-roberto-lucea-matrimonio-lr-milano-sala-specchi-cascina-pietrasanta-magenta-bn-018.webp", alt: "Matrimonio di Laura e Roberto a Magenta" },
      { src: "/media/images/lucea-2025-laura-roberto/lucea-2025-laura-roberto-lucea-matrimonio-lr-milano-sala-specchi-cascina-pietrasanta-magenta-bn-021.webp", alt: "Matrimonio di Laura e Roberto a Magenta" },
      { src: "/media/images/lucea-2025-laura-roberto/lucea-2025-laura-roberto-lucea-matrimonio-lr-milano-sala-specchi-cascina-pietrasanta-magenta-bn-024.webp", alt: "Matrimonio di Laura e Roberto a Magenta" },
      { src: "/media/images/lucea-2025-laura-roberto/lucea-2025-laura-roberto-lucea-matrimonio-lr-milano-sala-specchi-cascina-pietrasanta-magenta-bn-027.webp", alt: "Matrimonio di Laura e Roberto a Magenta" },
    ]),
  },
  {
    slug: "matrimonio-jinet-boris-oltrepo",
    title: "Il cuore di Jinet e Boris nelle colline dell'Oltrepò",
    location: "O.P. Paolo Pini, Milano · Agriturismo Melo Rosso, Fortunago, Oltrepò Pavese",
    dateLabel: "7 giugno 2025",
    image: "/media/images/lucea-2025-jinet-boris/lucea-2025-jinet-boris-lucea-matrimonio-jb-milano-agriturismo-melo-rosso-fortunago-oltrepo-023.webp",
    alt: "Matrimonio di Jinet e Boris tra Milano e l'Oltrepò Pavese",
    summary: "Cerimonia al Paolo Pini, 2CV verso Fortunago e festa tra le vigne: il matrimonio internazionale di Jinet e Boris.",
    paragraphs: [
      "Boris, olandese, e Jinet, iraniana. Lo dico subito: LUCEA ha un debole per i matrimoni interculturali! Quelle feste in cui si sente apertura, si respira aria fresca e dove amore, gioia e divertimento parlano un'unica lingua.",
      "Jinet è cantante, canta amore e speranza: con Boris hanno celebrato la cerimonia sul palco della festa “All You Need Is Pop” di Radio Popolare, a Milano. Poi sono partiti con una Citroën 2CV verso l'Oltrepò Pavese, dove li attendeva una location da sogno: l'Agriturismo Melo Rosso di Fortunago.",
      "Tra le vigne sulle colline dell'Oltrepò, un gruppo intimo di familiari e amici ha condiviso la loro gioia fino a notte fonda, accompagnato dalla musica degli Slide Pistons di Raffaele Kohler e Luciano Macchia. Un matrimonio internazionale, spontaneo e pieno di musica, emozioni e amici. Tutto un sogno durato, per qualcuno, fino alla colazione con gli sposi la mattina seguente!",
    ],
    gallery: coverFirst("/media/images/lucea-2025-jinet-boris/lucea-2025-jinet-boris-lucea-matrimonio-jb-milano-agriturismo-melo-rosso-fortunago-oltrepo-023.webp", "Matrimonio di Jinet e Boris tra Milano e l'Oltrepò Pavese", [
      { src: "/media/images/lucea-2025-jinet-boris/lucea-2025-jinet-boris-lucea-matrimonio-jb-milano-agriturismo-melo-rosso-fortunago-oltrepo-023.webp", alt: "Matrimonio di Jinet e Boris tra Milano e l'Oltrepò Pavese" },
      { src: "/media/images/lucea-2025-jinet-boris/lucea-2025-jinet-boris-lucea-matrimonio-jb-milano-agriturismo-melo-rosso-fortunago-oltrepo-001.webp", alt: "Matrimonio di Jinet e Boris in Oltrepò" },
      { src: "/media/images/lucea-2025-jinet-boris/lucea-2025-jinet-boris-lucea-matrimonio-jb-milano-agriturismo-melo-rosso-fortunago-oltrepo-003.webp", alt: "Matrimonio di Jinet e Boris in Oltrepò" },
      { src: "/media/images/lucea-2025-jinet-boris/lucea-2025-jinet-boris-lucea-matrimonio-jb-milano-agriturismo-melo-rosso-fortunago-oltrepo-005.webp", alt: "Matrimonio di Jinet e Boris in Oltrepò" },
      { src: "/media/images/lucea-2025-jinet-boris/lucea-2025-jinet-boris-lucea-matrimonio-jb-milano-agriturismo-melo-rosso-fortunago-oltrepo-007.webp", alt: "Matrimonio di Jinet e Boris in Oltrepò" },
      { src: "/media/images/lucea-2025-jinet-boris/lucea-2025-jinet-boris-lucea-matrimonio-jb-milano-agriturismo-melo-rosso-fortunago-oltrepo-009.webp", alt: "Matrimonio di Jinet e Boris in Oltrepò" },
      { src: "/media/images/lucea-2025-jinet-boris/lucea-2025-jinet-boris-lucea-matrimonio-jb-milano-agriturismo-melo-rosso-fortunago-oltrepo-011.webp", alt: "Matrimonio di Jinet e Boris in Oltrepò" },
      { src: "/media/images/lucea-2025-jinet-boris/lucea-2025-jinet-boris-lucea-matrimonio-jb-milano-agriturismo-melo-rosso-fortunago-oltrepo-014.webp", alt: "Matrimonio di Jinet e Boris in Oltrepò" },
      { src: "/media/images/lucea-2025-jinet-boris/lucea-2025-jinet-boris-lucea-matrimonio-jb-milano-agriturismo-melo-rosso-fortunago-oltrepo-016.webp", alt: "Matrimonio di Jinet e Boris in Oltrepò" },
      { src: "/media/images/lucea-2025-jinet-boris/lucea-2025-jinet-boris-lucea-matrimonio-jb-milano-agriturismo-melo-rosso-fortunago-oltrepo-018.webp", alt: "Matrimonio di Jinet e Boris in Oltrepò" },
      { src: "/media/images/lucea-2025-jinet-boris/lucea-2025-jinet-boris-lucea-matrimonio-jb-milano-agriturismo-melo-rosso-fortunago-oltrepo-020.webp", alt: "Matrimonio di Jinet e Boris in Oltrepò" },
      { src: "/media/images/lucea-2025-jinet-boris/lucea-2025-jinet-boris-lucea-matrimonio-jb-milano-agriturismo-melo-rosso-fortunago-oltrepo-022.webp", alt: "Matrimonio di Jinet e Boris in Oltrepò" },
      { src: "/media/images/lucea-2025-jinet-boris/lucea-2025-jinet-boris-lucea-matrimonio-jb-milano-agriturismo-melo-rosso-fortunago-oltrepo-025.webp", alt: "Matrimonio di Jinet e Boris in Oltrepò" },
      { src: "/media/images/lucea-2025-jinet-boris/lucea-2025-jinet-boris-lucea-matrimonio-jb-milano-agriturismo-melo-rosso-fortunago-oltrepo-027.webp", alt: "Matrimonio di Jinet e Boris in Oltrepò" },
      { src: "/media/images/lucea-2025-jinet-boris/lucea-2025-jinet-boris-lucea-matrimonio-jb-milano-agriturismo-melo-rosso-fortunago-oltrepo-029.webp", alt: "Matrimonio di Jinet e Boris in Oltrepò" },
      { src: "/media/images/lucea-2025-jinet-boris/lucea-2025-jinet-boris-lucea-matrimonio-jb-milano-agriturismo-melo-rosso-fortunago-oltrepo-031.webp", alt: "Matrimonio di Jinet e Boris in Oltrepò" },
      { src: "/media/images/lucea-2025-jinet-boris/lucea-2025-jinet-boris-lucea-matrimonio-jb-milano-agriturismo-melo-rosso-fortunago-oltrepo-033.webp", alt: "Matrimonio di Jinet e Boris in Oltrepò" },
      { src: "/media/images/lucea-2025-jinet-boris/lucea-2025-jinet-boris-lucea-matrimonio-jb-milano-agriturismo-melo-rosso-fortunago-oltrepo-035.webp", alt: "Matrimonio di Jinet e Boris in Oltrepò" },
      { src: "/media/images/lucea-2025-jinet-boris/lucea-2025-jinet-boris-lucea-matrimonio-jb-milano-agriturismo-melo-rosso-fortunago-oltrepo-038.webp", alt: "Matrimonio di Jinet e Boris in Oltrepò" },
      { src: "/media/images/lucea-2025-jinet-boris/lucea-2025-jinet-boris-lucea-matrimonio-jb-milano-agriturismo-melo-rosso-fortunago-oltrepo-040.webp", alt: "Matrimonio di Jinet e Boris in Oltrepò" },
      { src: "/media/images/lucea-2025-jinet-boris/lucea-2025-jinet-boris-lucea-matrimonio-jb-milano-agriturismo-melo-rosso-fortunago-oltrepo-042.webp", alt: "Matrimonio di Jinet e Boris in Oltrepò" },
      { src: "/media/images/lucea-2025-jinet-boris/lucea-2025-jinet-boris-lucea-matrimonio-jb-milano-agriturismo-melo-rosso-fortunago-oltrepo-044.webp", alt: "Matrimonio di Jinet e Boris in Oltrepò" },
      { src: "/media/images/lucea-2025-jinet-boris/lucea-2025-jinet-boris-lucea-matrimonio-jb-milano-agriturismo-melo-rosso-fortunago-oltrepo-046.webp", alt: "Matrimonio di Jinet e Boris in Oltrepò" },
      { src: "/media/images/lucea-2025-jinet-boris/lucea-2025-jinet-boris-lucea-matrimonio-jb-milano-agriturismo-melo-rosso-fortunago-oltrepo-049.webp", alt: "Matrimonio di Jinet e Boris in Oltrepò" },
      { src: "/media/images/lucea-2025-jinet-boris/lucea-2025-jinet-boris-lucea-matrimonio-jb-milano-agriturismo-melo-rosso-fortunago-oltrepo-051.webp", alt: "Matrimonio di Jinet e Boris in Oltrepò" },
      { src: "/media/images/lucea-2025-jinet-boris/lucea-2025-jinet-boris-lucea-matrimonio-jb-milano-agriturismo-melo-rosso-fortunago-oltrepo-053.webp", alt: "Matrimonio di Jinet e Boris in Oltrepò" },
      { src: "/media/images/lucea-2025-jinet-boris/lucea-2025-jinet-boris-lucea-matrimonio-jb-milano-agriturismo-melo-rosso-fortunago-oltrepo-055.webp", alt: "Matrimonio di Jinet e Boris in Oltrepò" },
      { src: "/media/images/lucea-2025-jinet-boris/lucea-2025-jinet-boris-lucea-matrimonio-jb-milano-agriturismo-melo-rosso-fortunago-oltrepo-057.webp", alt: "Matrimonio di Jinet e Boris in Oltrepò" },
      { src: "/media/images/lucea-2025-jinet-boris/lucea-2025-jinet-boris-lucea-matrimonio-jb-milano-agriturismo-melo-rosso-fortunago-oltrepo-060.webp", alt: "Matrimonio di Jinet e Boris in Oltrepò" },
    ]),
  },
  {
    slug: "matrimonio-michi-tia-villa-ghiringhelli",
    title: "Il matrimonio di Michi e Tia a Villa Ghiringhelli",
    location: "Azzate, Varese · Villa Ghiringhelli",
    dateLabel: "29 agosto 2025",
    image: "/media/images/lucea-2025-michi-e-tia/lucea-2025-michi-e-tia-wedding-lucea-matrimonio-mm-villa-ghiringhelli-varese-azzate-036.webp",
    alt: "Matrimonio di Michi e Tia a Villa Ghiringhelli",
    summary: "Duecento invitati, cerimonia sotto la pioggia e una festa da stadio a Villa Ghiringhelli.",
    paragraphs: [
      "Avevo già incontrato Michi e Tia per [le foto pre-matrimonio nei boschi di Cantù](/storie/prewedding-michi-tia-boschi-cantu) e ora l'appuntamento era quello del matrimonio.",
      "Fine agosto, nuvole nere, gocce di pioggia e ombrelli illuminati dal sole radente durante la cerimonia civile all'aperto, in uno scenario magico, dove gli sposi, circondati da 200 invitati, hanno potuto vivere e mostrarci tutta la loro felicità. Ci siamo presi un momento breve per alcune foto di coppia e con i vari gruppetti di amici che facevano a gara per esserci. Giusto il tempo di finire questo momento di divertimento, che si è scatenato il diluvio.",
      "Ma era l'ora di cena, all'interno di Villa Ghiringhelli. Michi e Tia non si sono scomposti neanche un po'. La pioggia non ha cambiato il loro buon umore, e nemmeno il nostro: anzi! Da bravi ex scout hanno saputo rendere anche quello un momento ancora più speciale. Sole, pozzanghere, lacrime, balli, risate, temporale, amici – tifo da stadio! – DJ set. Tutto è stato pieno di quell'energia da matrimonio giovane, e noi non ce ne siamo persi nemmeno un minuto con le nostre foto e il video.",
    ],
    related: { slug: "prewedding-michi-tia-boschi-cantu", label: "le foto pre-matrimonio nei boschi di Cantù" },
    gallery: coverFirst("/media/images/lucea-2025-michi-e-tia/lucea-2025-michi-e-tia-wedding-lucea-matrimonio-mm-villa-ghiringhelli-varese-azzate-036.webp", "Matrimonio di Michi e Tia a Villa Ghiringhelli", [
      { src: "/media/images/lucea-2025-michi-e-tia/lucea-2025-michi-e-tia-wedding-lucea-matrimonio-mm-villa-ghiringhelli-varese-azzate-036.webp", alt: "Matrimonio di Michi e Tia a Villa Ghiringhelli" },
      { src: "/media/images/lucea-2025-michi-e-tia/lucea-2025-michi-e-tia-wedding-lucea-matrimonio-mm-villa-ghiringhelli-varese-azzate-006.webp", alt: "Matrimonio di Michi e Tia a Villa Ghiringhelli" },
      { src: "/media/images/lucea-2025-michi-e-tia/lucea-2025-michi-e-tia-wedding-lucea-matrimonio-mm-villa-ghiringhelli-varese-azzate-001.webp", alt: "Matrimonio di Michi e Tia a Villa Ghiringhelli" },
      { src: "/media/images/lucea-2025-michi-e-tia/lucea-2025-michi-e-tia-wedding-lucea-matrimonio-mm-villa-ghiringhelli-varese-azzate-005.webp", alt: "Matrimonio di Michi e Tia a Villa Ghiringhelli" },
      { src: "/media/images/lucea-2025-michi-e-tia/lucea-2025-michi-e-tia-wedding-lucea-matrimonio-mm-villa-ghiringhelli-varese-azzate-008.webp", alt: "Matrimonio di Michi e Tia a Villa Ghiringhelli" },
      { src: "/media/images/lucea-2025-michi-e-tia/lucea-2025-michi-e-tia-wedding-lucea-matrimonio-mm-villa-ghiringhelli-varese-azzate-011.webp", alt: "Matrimonio di Michi e Tia a Villa Ghiringhelli" },
      { src: "/media/images/lucea-2025-michi-e-tia/lucea-2025-michi-e-tia-wedding-lucea-matrimonio-mm-villa-ghiringhelli-varese-azzate-014.webp", alt: "Matrimonio di Michi e Tia a Villa Ghiringhelli" },
      { src: "/media/images/lucea-2025-michi-e-tia/lucea-2025-michi-e-tia-wedding-lucea-matrimonio-mm-villa-ghiringhelli-varese-azzate-017.webp", alt: "Matrimonio di Michi e Tia a Villa Ghiringhelli" },
      { src: "/media/images/lucea-2025-michi-e-tia/lucea-2025-michi-e-tia-wedding-lucea-matrimonio-mm-villa-ghiringhelli-varese-azzate-020.webp", alt: "Matrimonio di Michi e Tia a Villa Ghiringhelli" },
      { src: "/media/images/lucea-2025-michi-e-tia/lucea-2025-michi-e-tia-wedding-lucea-matrimonio-mm-villa-ghiringhelli-varese-azzate-024.webp", alt: "Matrimonio di Michi e Tia a Villa Ghiringhelli" },
      { src: "/media/images/lucea-2025-michi-e-tia/lucea-2025-michi-e-tia-wedding-lucea-matrimonio-mm-villa-ghiringhelli-varese-azzate-027.webp", alt: "Matrimonio di Michi e Tia a Villa Ghiringhelli" },
      { src: "/media/images/lucea-2025-michi-e-tia/lucea-2025-michi-e-tia-wedding-lucea-matrimonio-mm-villa-ghiringhelli-varese-azzate-030.webp", alt: "Matrimonio di Michi e Tia a Villa Ghiringhelli" },
      { src: "/media/images/lucea-2025-michi-e-tia/lucea-2025-michi-e-tia-wedding-lucea-matrimonio-mm-villa-ghiringhelli-varese-azzate-033.webp", alt: "Matrimonio di Michi e Tia a Villa Ghiringhelli" },
      { src: "/media/images/lucea-2025-michi-e-tia/lucea-2025-michi-e-tia-wedding-lucea-matrimonio-mm-villa-ghiringhelli-varese-azzate-039.webp", alt: "Matrimonio di Michi e Tia a Villa Ghiringhelli" },
      { src: "/media/images/lucea-2025-michi-e-tia/lucea-2025-michi-e-tia-wedding-lucea-matrimonio-mm-villa-ghiringhelli-varese-azzate-043.webp", alt: "Matrimonio di Michi e Tia a Villa Ghiringhelli" },
      { src: "/media/images/lucea-2025-michi-e-tia/lucea-2025-michi-e-tia-wedding-lucea-matrimonio-mm-villa-ghiringhelli-varese-azzate-046.webp", alt: "Matrimonio di Michi e Tia a Villa Ghiringhelli" },
      { src: "/media/images/lucea-2025-michi-e-tia/lucea-2025-michi-e-tia-wedding-lucea-matrimonio-mm-villa-ghiringhelli-varese-azzate-049.webp", alt: "Matrimonio di Michi e Tia a Villa Ghiringhelli" },
      { src: "/media/images/lucea-2025-michi-e-tia/lucea-2025-michi-e-tia-wedding-lucea-matrimonio-mm-villa-ghiringhelli-varese-azzate-052.webp", alt: "Matrimonio di Michi e Tia a Villa Ghiringhelli" },
      { src: "/media/images/lucea-2025-michi-e-tia/lucea-2025-michi-e-tia-wedding-lucea-matrimonio-mm-villa-ghiringhelli-varese-azzate-055.webp", alt: "Matrimonio di Michi e Tia a Villa Ghiringhelli" },
      { src: "/media/images/lucea-2025-michi-e-tia/lucea-2025-michi-e-tia-wedding-lucea-matrimonio-mm-villa-ghiringhelli-varese-azzate-058.webp", alt: "Matrimonio di Michi e Tia a Villa Ghiringhelli" },
      { src: "/media/images/lucea-2025-michi-e-tia/lucea-2025-michi-e-tia-wedding-lucea-matrimonio-mm-villa-ghiringhelli-varese-azzate-062.webp", alt: "Matrimonio di Michi e Tia a Villa Ghiringhelli" },
      { src: "/media/images/lucea-2025-michi-e-tia/lucea-2025-michi-e-tia-wedding-lucea-matrimonio-mm-villa-ghiringhelli-varese-azzate-065.webp", alt: "Matrimonio di Michi e Tia a Villa Ghiringhelli" },
      { src: "/media/images/lucea-2025-michi-e-tia/lucea-2025-michi-e-tia-wedding-lucea-matrimonio-mm-villa-ghiringhelli-varese-azzate-068.webp", alt: "Matrimonio di Michi e Tia a Villa Ghiringhelli" },
      { src: "/media/images/lucea-2025-michi-e-tia/lucea-2025-michi-e-tia-wedding-lucea-matrimonio-mm-villa-ghiringhelli-varese-azzate-071.webp", alt: "Matrimonio di Michi e Tia a Villa Ghiringhelli" },
      { src: "/media/images/lucea-2025-michi-e-tia/lucea-2025-michi-e-tia-wedding-lucea-matrimonio-mm-villa-ghiringhelli-varese-azzate-074.webp", alt: "Matrimonio di Michi e Tia a Villa Ghiringhelli" },
      { src: "/media/images/lucea-2025-michi-e-tia/lucea-2025-michi-e-tia-wedding-lucea-matrimonio-mm-villa-ghiringhelli-varese-azzate-077.webp", alt: "Matrimonio di Michi e Tia a Villa Ghiringhelli" },
      { src: "/media/images/lucea-2025-michi-e-tia/lucea-2025-michi-e-tia-wedding-lucea-matrimonio-mm-villa-ghiringhelli-varese-azzate-081.webp", alt: "Matrimonio di Michi e Tia a Villa Ghiringhelli" },
      { src: "/media/images/lucea-2025-michi-e-tia/lucea-2025-michi-e-tia-wedding-lucea-matrimonio-mm-villa-ghiringhelli-varese-azzate-084.webp", alt: "Matrimonio di Michi e Tia a Villa Ghiringhelli" },
      { src: "/media/images/lucea-2025-michi-e-tia/lucea-2025-michi-e-tia-wedding-lucea-matrimonio-mm-villa-ghiringhelli-varese-azzate-087.webp", alt: "Matrimonio di Michi e Tia a Villa Ghiringhelli" },
      { src: "/media/images/lucea-2025-michi-e-tia/lucea-2025-michi-e-tia-wedding-lucea-matrimonio-mm-villa-ghiringhelli-varese-azzate-090.webp", alt: "Matrimonio di Michi e Tia a Villa Ghiringhelli" },
      { src: "/media/images/lucea-2025-michi-e-tia/lucea-2025-michi-e-tia-wedding-lucea-matrimonio-mm-villa-ghiringhelli-varese-azzate-093.webp", alt: "Matrimonio di Michi e Tia a Villa Ghiringhelli" },
      { src: "/media/images/lucea-2025-michi-e-tia/lucea-2025-michi-e-tia-wedding-lucea-matrimonio-mm-villa-ghiringhelli-varese-azzate-097.webp", alt: "Matrimonio di Michi e Tia a Villa Ghiringhelli" },
    ]),
  },
  {
    slug: "matrimonio-liz-luca-mapello",
    title: "Liz e Luca a Villa Martinelli",
    location: "Villa Martinelli, Mapello, Bergamo",
    dateLabel: "6 giugno 2026",
    image: "/media/images/lucea-2026-liz-luca/lucea-2026-liz-luca-lucea-matrimonio-ll-bergamo-mapello-villa-martinelli-068.webp",
    alt: "Matrimonio di Liz e Luca a Villa Martinelli, Mapello",
    summary: "Tra Bergamo e Corea, una festa interculturale a Villa Martinelli, raccontata da un solo fotografo.",
    paragraphs: [
      "Un matrimonio interculturale si sente: è come se ci fosse una porta aperta sul mondo! Quando gli invitati hanno origini diverse e magari arrivano in Italia per la prima volta — dalla Corea, ad esempio! — la festa si riempie di momenti freschi, nuovi, inaspettati. Cambiano le musiche, la cerimonia si arricchisce di abitudini mai viste prima, la curiosità aleggia tra tutti i presenti e le lingue si mischiano.",
      "Tutto questo è successo con Luca e Liz, tra Bergamo e Corea, in una festa piena di amici celebrata nella meravigliosa Villa Martinelli di Mapello.",
      "Hanno desiderato un solo fotografo per raccontare il loro matrimonio: ci sono andato io e non sapevo più dove puntare la macchina fotografica, tante erano le occasioni per cogliere momenti nuovi e raccontare la loro splendida giornata!",
    ],
    gallery: coverFirst("/media/images/lucea-2026-liz-luca/lucea-2026-liz-luca-lucea-matrimonio-ll-bergamo-mapello-villa-martinelli-068.webp", "Matrimonio di Liz e Luca a Villa Martinelli, Mapello", [
      { src: "/media/images/lucea-2026-liz-luca/lucea-2026-liz-luca-lucea-matrimonio-ll-bergamo-mapello-villa-martinelli-029.webp", alt: "Matrimonio di Liz e Luca a Mapello" },
      { src: "/media/images/lucea-2026-liz-luca/lucea-2026-liz-luca-lucea-matrimonio-ll-bergamo-mapello-villa-martinelli-001.webp", alt: "Matrimonio di Liz e Luca a Mapello" },
      { src: "/media/images/lucea-2026-liz-luca/lucea-2026-liz-luca-lucea-matrimonio-ll-bergamo-mapello-villa-martinelli-003.webp", alt: "Matrimonio di Liz e Luca a Mapello" },
      { src: "/media/images/lucea-2026-liz-luca/lucea-2026-liz-luca-lucea-matrimonio-ll-bergamo-mapello-villa-martinelli-005.webp", alt: "Matrimonio di Liz e Luca a Mapello" },
      { src: "/media/images/lucea-2026-liz-luca/lucea-2026-liz-luca-lucea-matrimonio-ll-bergamo-mapello-villa-martinelli-008.webp", alt: "Matrimonio di Liz e Luca a Mapello" },
      { src: "/media/images/lucea-2026-liz-luca/lucea-2026-liz-luca-lucea-matrimonio-ll-bergamo-mapello-villa-martinelli-010.webp", alt: "Matrimonio di Liz e Luca a Mapello" },
      { src: "/media/images/lucea-2026-liz-luca/lucea-2026-liz-luca-lucea-matrimonio-ll-bergamo-mapello-villa-martinelli-013.webp", alt: "Matrimonio di Liz e Luca a Mapello" },
      { src: "/media/images/lucea-2026-liz-luca/lucea-2026-liz-luca-lucea-matrimonio-ll-bergamo-mapello-villa-martinelli-015.webp", alt: "Matrimonio di Liz e Luca a Mapello" },
      { src: "/media/images/lucea-2026-liz-luca/lucea-2026-liz-luca-lucea-matrimonio-ll-bergamo-mapello-villa-martinelli-017.webp", alt: "Matrimonio di Liz e Luca a Mapello" },
      { src: "/media/images/lucea-2026-liz-luca/lucea-2026-liz-luca-lucea-matrimonio-ll-bergamo-mapello-villa-martinelli-020.webp", alt: "Matrimonio di Liz e Luca a Mapello" },
      { src: "/media/images/lucea-2026-liz-luca/lucea-2026-liz-luca-lucea-matrimonio-ll-bergamo-mapello-villa-martinelli-022.webp", alt: "Matrimonio di Liz e Luca a Mapello" },
      { src: "/media/images/lucea-2026-liz-luca/lucea-2026-liz-luca-lucea-matrimonio-ll-bergamo-mapello-villa-martinelli-025.webp", alt: "Matrimonio di Liz e Luca a Mapello" },
      { src: "/media/images/lucea-2026-liz-luca/lucea-2026-liz-luca-lucea-matrimonio-ll-bergamo-mapello-villa-martinelli-027.webp", alt: "Matrimonio di Liz e Luca a Mapello" },
      { src: "/media/images/lucea-2026-liz-luca/lucea-2026-liz-luca-lucea-matrimonio-ll-bergamo-mapello-villa-martinelli-030.webp", alt: "Matrimonio di Liz e Luca a Mapello" },
      { src: "/media/images/lucea-2026-liz-luca/lucea-2026-liz-luca-lucea-matrimonio-ll-bergamo-mapello-villa-martinelli-032.webp", alt: "Matrimonio di Liz e Luca a Mapello" },
      { src: "/media/images/lucea-2026-liz-luca/lucea-2026-liz-luca-lucea-matrimonio-ll-bergamo-mapello-villa-martinelli-034.webp", alt: "Matrimonio di Liz e Luca a Mapello" },
      { src: "/media/images/lucea-2026-liz-luca/lucea-2026-liz-luca-lucea-matrimonio-ll-bergamo-mapello-villa-martinelli-037.webp", alt: "Matrimonio di Liz e Luca a Mapello" },
      { src: "/media/images/lucea-2026-liz-luca/lucea-2026-liz-luca-lucea-matrimonio-ll-bergamo-mapello-villa-martinelli-039.webp", alt: "Matrimonio di Liz e Luca a Mapello" },
      { src: "/media/images/lucea-2026-liz-luca/lucea-2026-liz-luca-lucea-matrimonio-ll-bergamo-mapello-villa-martinelli-042.webp", alt: "Matrimonio di Liz e Luca a Mapello" },
      { src: "/media/images/lucea-2026-liz-luca/lucea-2026-liz-luca-lucea-matrimonio-ll-bergamo-mapello-villa-martinelli-044.webp", alt: "Matrimonio di Liz e Luca a Mapello" },
      { src: "/media/images/lucea-2026-liz-luca/lucea-2026-liz-luca-lucea-matrimonio-ll-bergamo-mapello-villa-martinelli-046.webp", alt: "Matrimonio di Liz e Luca a Mapello" },
      { src: "/media/images/lucea-2026-liz-luca/lucea-2026-liz-luca-lucea-matrimonio-ll-bergamo-mapello-villa-martinelli-049.webp", alt: "Matrimonio di Liz e Luca a Mapello" },
      { src: "/media/images/lucea-2026-liz-luca/lucea-2026-liz-luca-lucea-matrimonio-ll-bergamo-mapello-villa-martinelli-051.webp", alt: "Matrimonio di Liz e Luca a Mapello" },
      { src: "/media/images/lucea-2026-liz-luca/lucea-2026-liz-luca-lucea-matrimonio-ll-bergamo-mapello-villa-martinelli-054.webp", alt: "Matrimonio di Liz e Luca a Mapello" },
      { src: "/media/images/lucea-2026-liz-luca/lucea-2026-liz-luca-lucea-matrimonio-ll-bergamo-mapello-villa-martinelli-056.webp", alt: "Matrimonio di Liz e Luca a Mapello" },
      { src: "/media/images/lucea-2026-liz-luca/lucea-2026-liz-luca-lucea-matrimonio-ll-bergamo-mapello-villa-martinelli-059.webp", alt: "Matrimonio di Liz e Luca a Mapello" },
      { src: "/media/images/lucea-2026-liz-luca/lucea-2026-liz-luca-lucea-matrimonio-ll-bergamo-mapello-villa-martinelli-061.webp", alt: "Matrimonio di Liz e Luca a Mapello" },
      { src: "/media/images/lucea-2026-liz-luca/lucea-2026-liz-luca-lucea-matrimonio-ll-bergamo-mapello-villa-martinelli-063.webp", alt: "Matrimonio di Liz e Luca a Mapello" },
      { src: "/media/images/lucea-2026-liz-luca/lucea-2026-liz-luca-lucea-matrimonio-ll-bergamo-mapello-villa-martinelli-066.webp", alt: "Matrimonio di Liz e Luca a Mapello" },
      { src: "/media/images/lucea-2026-liz-luca/lucea-2026-liz-luca-lucea-matrimonio-ll-bergamo-mapello-villa-martinelli-068.webp", alt: "Matrimonio di Liz e Luca a Villa Martinelli, Mapello" },
      { src: "/media/images/lucea-2026-liz-luca/lucea-2026-liz-luca-lucea-matrimonio-ll-bergamo-mapello-villa-martinelli-071.webp", alt: "Matrimonio di Liz e Luca a Mapello" },
      { src: "/media/images/lucea-2026-liz-luca/lucea-2026-liz-luca-lucea-matrimonio-ll-bergamo-mapello-villa-martinelli-073.webp", alt: "Matrimonio di Liz e Luca a Mapello" },
      { src: "/media/images/lucea-2026-liz-luca/lucea-2026-liz-luca-lucea-matrimonio-ll-bergamo-mapello-villa-martinelli-076.webp", alt: "Matrimonio di Liz e Luca a Mapello" },
    ]),
  },
];

/** Più recenti in cima (lista /storie). */
export const storiesNewestFirst = [...stories].reverse();
